spring:
  application:
    name: kolokipa-backend
  profiles:
    active: local

jwt:
  secret: "change-this-to-a-long-random-string-at-least-32-characters-for-security"
  expiration-minutes: 1440